import { OutputTransformer } from '.'

export const addPreambleOutputTransformer: OutputTransformer = (output, cfg) => {
  return [
    '/* Autogenerated file. Do not edit manually. */',
    cfg.flags.tsNocheck && '// @ts-nocheck',
    '/* tslint:disable */',
    '/* eslint-disable */',
    output,
  ]
    .filter(Boolean)
    .join('\n')
}
