/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iSimpleToken from "./ISimpleToken";
export type { iSimpleToken };
import type * as issue552Reproduction from "./Issue552_Reproduction";
export type { issue552Reproduction };
import type * as kingOfTheHill from "./KingOfTheHill";
export type { kingOfTheHill };
import type * as rarity from "./Rarity";
export type { rarity };
import type * as simpleToken from "./SimpleToken";
export type { simpleToken };
import type * as nested from "./nested";
export type { nested };
