/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as payable from "./Payable";
export type { payable };
import type * as payableFactory from "./PayableFactory";
export type { payableFactory };
